{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "microservice.name" . | default .Chart.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: {{ include "microservice.name" . | default .Chart.Name }}
{{- with .Values.hpa }}
  minReplicas: {{ .minReplicas }}
  maxReplicas: {{ .maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .cpuUtilization }}
    - type: Resource
      resource:
        name: memory
        targetAverageValue: "{{ .memoryUtilization }}"
{{- end }}
{{- end }}
