{{- if .Values.secrets.enabled }} 
apiVersion: v1
data:
  tls.crt: public_crt_encoded
  tls.key: key_encoded
kind: Secret
metadata:
  name: {{ .Values.secrets.atlas }}
  namespace: {{ .Values.ns_name }}
type: kubernetes.io/tls
{{- end }}
