{{- if .Values.secrets.enabled }}
apiVersion: v1
data:
  {{- with .Values.vault }} 
  VAULT_ROLE_ID: {{ .role_id | b64enc }}
  VAULT_SECRET_ID: {{ .secret_id | b64enc }}
  {{- end }}
kind: Secret
metadata:
  name: {{ .Values.secrets.vault_secret_name }}
  namespace: {{ .Values.ns_name }}
type: Opaque
{{- end }}
