replicaCount: 1

ms_names: 
  name: ms-auth

ns_name: atlas

strategy:
  enabled: true
  type: RollingUpdate
  rollingUpdate: #Update Pods a certain number at a time
    maxUnavailable: 0 #Total number of pods that can be unavailable at once
    maxSurge: 1 #Maximum number of pods that can be deployed above desired state
minReadySeconds: 5
revisionHistoryLimit: 3


hpa:
  enabled: true
  minReplicas: "2"
  maxReplicas: "6"
  cpuUtilization: "90"
  memoryUtilization: "1500Mi"

ingress:
  enabled: false
  hostname: optimus.kapitalbank.az
  name: kbworkplace
  routes: 
    - route: /
      name: kb-workplace
      port: 8080
    - route: /api
      name: gw-branch
      port: 80
  lbip: 10.0.80.70

secrets:
  enabled: true
  apis:
    - name: HOST
      fieldPath: status.hostIP
    - name: POD_NAME
      fieldPath: metadata.name
    - name: POD_NAMESPACE
      fieldPath: metadata.namespace
  vaults:
    - name: VAULT_ROLE_ID
      valueFrom:
        name: secret-vault
        key: VAULT_ROLE_ID
    - name: VAULT_SECRET_ID
      valueFrom:
        name: secret-vault
        key: VAULT_SECRET_ID
  atlas: optimus-tls
  vault_secret_name: secret-vault

nessprobe:
  initialDelay: 60
  period: 10
  timeout: 5
  failure: 3
  success: 2


service:
  src_port: 80
  dst_port: 8080
  account_name: atlas-sa 
  actuator_path: actuator/health

deploy_env: dev

resource:
  limits:
    cpu: 0
    memory: 2000Mi
  requests:
    cpu: 0
    memory: 1500Mi

image:
  repo_url: nexus.kblab.local:8083/v1/repositories
  repo_name: kblab
  image_vers: latest

metallb:
  enabled: false
  address_pool: 
    start: 10.0.80.70
    end: 10.0.80.80
  ns_name: metallb-system
  name: metallbconfig
  pool_name: prodmetallbpool

vault:
  role_id: elmehetdi
  secret_id: kadime

